Refactor Pay Launcher API
cafebazaar/BazaarPay pull request #21
Opened 2023-03-21 02:51 UTC by alibagherifam

The API surface of the `BazaarPayLauncher` object, refactored in [this](https://github.com/cafebazaar/BazaarPay/commit/a8d490e60c8b549b4a7e6f6e7a20900c8099b12d) commit, does not leverage the full potential of the [Activity Result API](https://developer.android.com/training/basics/intents/result). This PR introduces `BazaarPayContract` class that provides the following advantages over the mentioned object:

- No need to pass `Context` and `ActivityResultLauncher` when launching a payment.
- No need to notify `BazaarPayLauncher` about the incoming `ActivityResult` manually.
- Fully documented with *KDoc*, which opens the potential for [Dokka](https://kotlinlang.org/docs/dokka-introduction.html) integration in the future.
- Encapsulates payment flow options into a separate data class (`BazaarPayOptions`) that enables adding *Factory* or *Builder* patterns when options grow.
- No need to allocate an extra object without any internal state.
- It is similar to built-in [Activity Result Contracts](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts), which are familiar to most android developers.

> Note:
> This PR only marks the `BazaarPayLauncher` object as deprecated and does not remove that for backward compatibility reasons.

2023-04-04 20:21 UTC, alibagherifam commented
@hamidrezasahraei 
I've resolved the merge conflict and made the necessary changes. The pull request is now ready for your review.
Please let me know if there's anything else that needs to be addressed.

2023-04-05 10:25 UTC, hamidrezasahraei requested changes

2023-04-05 10:25 UTC, hamidrezasahraei commented on BazaarPay/src/main/java/ir/cafebazaar/bazaarpay/StartBazaarPay.kt
> +class StartBazaarPay : ActivityResultContract<BazaarPayOptions, Boolean>() {
@alibagherifam 
I think it would be nicer if you change this class name to `StartBazaarPayContrcat` to point out that this class is a contract.

2023-04-05 10:25 UTC, hamidrezasahraei commented on BazaarPay/src/main/java/ir/cafebazaar/bazaarpay/BazaarPayLauncher.kt
> +    message = "Use the BazaarPayContract class instead",
@alibagherifam 
There is no class with this name, I think it should be `StartBazaarPay`, Btw if you change the `StartBazaarPay` class name be aware that you should change this too to the new name.
Also, I think it would be nicer if you can link this class with `@link` in the message too.(if possible)

2023-04-05 11:58 UTC, alibagherifam commented on BazaarPay/src/main/java/ir/cafebazaar/bazaarpay/StartBazaarPay.kt
> +class StartBazaarPay : ActivityResultContract<BazaarPayOptions, Boolean>() {
@hamidrezasahraei 
That was my first perception, too, as I named the class `BazaarPayContract` in the first place. But I discovered that the [pre-built contracts](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts) in the Activity Result API are **all** named imperatively  without the word "contract" as a postfix, representing an action that the user or the app can take, such as `TakePicture`, `CreateDocument`, or `RequestPermission`. The documentation even uses this naming convention for `PickRington` as an example of a [custom contract](https://developer.android.com/training/basics/intents/result#custom).

That was why I renamed the class to `StartBazaarPay` but forgot to reflect this change in the deprecation message of `BazaarPayLauncher`. Although it is the naming convention that Android suggests for Activity Result Contracts, it may not be fit for this project, and you may prefer to name the class in another way. Please let me know your opinion on the naming and whether I should rename the class.

2023-04-05 13:45 UTC, alibagherifam commented on BazaarPay/src/main/java/ir/cafebazaar/bazaarpay/BazaarPayLauncher.kt
> +    message = "Use the BazaarPayContract class instead",
@hamidrezasahraei 
Thank you for reviewing my pull request and catching that mistake. I apologize for any confusion caused by the class name typo; I have already corrected it to `StartBazaarPay`. Previously I renamed the `BazaarPayContract` to `StartBazaarPay` in [this commit](https://github.com/cafebazaar/BazaarPay/pull/21/commits/9d918766d0234c3b3ae6b5438fc721615700a48c), but forgot to reflect this change in the deprecation message of `BazaarPayLauncher`. If the class needs to be renamed after the [conversation on the naming](https://github.com/cafebazaar/BazaarPay/pull/21#discussion_r1158323163) , I will remember to change the deprecation message too.

For linking the class in the message, `@link` tag in Javadoc or the `[ ]` syntax in KDoc is only available in the comment block but not in the message of the `@Deprecated` annotation. Also, according to the [KDoc syntax](https://kotlinlang.org/docs/kotlin-doc.html#suppress):
> KDoc does not support the `@deprecated` tag. Instead, please use the `@Deprecated` annotation.

Therefore the only way to add a link to the declaration of `StartBazaarPay` is to add a regular documentation block on the `BazaarPayLauncher`. So I have [added documentation](https://github.com/cafebazaar/BazaarPay/pull/21/commits/ae2ff56cd0c4ec36d9a2033acfd6c959a8e24bae)  on this class. I look forward to hearing your thoughts.

2023-04-06 09:20 UTC, hamidrezasahraei commented on BazaarPay/src/main/java/ir/cafebazaar/bazaarpay/BazaarPayLauncher.kt
> +    message = "Use the BazaarPayContract class instead",
Good point, I agree.

2023-04-06 09:22 UTC, hamidrezasahraei commented
@AlirezaSoltaniJazi 
We should test all payment flows in this PR.

2023-04-06 09:23 UTC, hamidrezasahraei approved these changes

2023-04-08 10:18 UTC, AlirezaSoltaniJazi commented
LGTM @hamidrezasahraei

2023-04-08 10:18 UTC, AlirezaSoltaniJazi approved these changes

2023-04-08 13:52 UTC, merged